Repository raide-project/ctf_public, pull requests merged in 2019-07, with the labels that each got.

#82 V2:: Extended State Representation
  cap_eval.py
  gym_cap/envs/agent.py
  gym_cap/envs/cap_env.py
  gym_cap/envs/const.py
  gym_cap/envs/create_map.py
  policy/__init__.py
  policy/astar_flag.py
  policy/defense.py
  policy/patrol.py
  policy/policy.py
  policy/roomba.py
  unittesting.py
Labels: PRIORITY, TODO, bug::urgent, optimize::core, organize::code

#94 Update on Advanced Policies
  policy/__init__.py
  policy/astar_flag.py
  policy/fighter.py
  policy/patrol.py
  policy/policy.py
Labels: feature::add-on, feature::request, optimize::minor, organize::code, update

#90 Spiral
  policy/__init__.py
  policy/policy.py
  policy/spiral.py
Labels: bug::need fix, update
