Repository raide-project/ctf_public, pull requests merged in 2019-05, with the labels that each got.

#15 Issue14 :: Bug in element placement
  gym_cap/envs/create_map.py
Labels: bug

#21 changes made so that UAV and UGV do not collide
  gym_cap/envs/agent.py
Labels: bug

#32 updated roomba.py
  policy/roomba.py
Labels: bug, easy fix

#34 Issue6: Customize Configuration
  README.md
  gym_cap/envs/cap_env.py
  gym_cap/envs/const.py
  gym_cap/envs/create_map.py
Labels: TODO, feature/enhancement, help wanted
