Repository raide-project/ctf_public, pull requests merged in 2019-06, with the labels that each got.

#39 Issue16: Update existence policies with blue perspective
  policy/defense.py
  policy/patrol.py
Labels: bug, update

#50 Patch 4: move all initialization in reset()
  cap_eval.py
  cap_test.py
  gym_cap/envs/cap_env.py
Labels: TODO, easy fix, feature/enhancement

#40 Issue12: Individual Memory
  gym_cap/envs/agent.py
  gym_cap/envs/cap_env.py
Labels: TODO, feature::enhancement

#57 hot fix: individual memory update using masking
  gym_cap/envs/agent.py
Labels: TODO, bug::minor, optimize::minor, update

#61 changed com variables to class variables
  gym_cap/envs/agent.py
Labels: organize::code, update

#59 Include global memory:: add individual memory and global memory in rendering
  gym_cap/envs/agent.py
  gym_cap/envs/cap_env.py
Labels: feature::add-on

#62 Include bias setting for stochastic interaction
  README.md
  gym_cap/envs/cap_env.py
  gym_cap/envs/const.py
Labels: feature::enhancement

#65 Issue54
  gym_cap/envs/agent.py
Labels: bug::minor

#69 Issue68::Add red control in step method
  gym_cap/envs/cap_env.py
Labels: TODO, feature::add-on

#71 Issue68:: Red control with step method
  gym_cap/envs/cap_env.py
  gym_cap/envs/const.py
Labels: TODO, bug::need fix, feature::enhancement

#72 Compatibility with python27
  gym_cap/envs/cap_env.py
  gym_cap/envs/create_map.py
Labels: bug::need fix, optimize::minor, update

#83 Unittest:: Gym build and basic run
  unittesting.py
Labels: unit test, update

#84 Marker in rendering
  gym_cap/envs/agent.py
  gym_cap/envs/cap_env.py
Labels: feature::enhancement, optimize::minor, organize::code
